# Generated by Django 5.2.1 on 2025-05-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articol', '0003_articoll_delete_articol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articoll',
        ),
    ]
