# Generated by Django 5.2.1 on 2025-05-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articol', '0004_delete_articoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articol_images/'),
        ),
    ]
