# Generated by Django 5.2.1 on 2025-05-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
